### ISSUE TITLE
Learn How to Use Zenhub

### ISSUE THREAD

**Issue by usman-hussain** [usman-hussain/UBEats#1]
Task:
-Learn how to use zenhub properly
-Think of 2 tickets to create

**Comment by usman-hussain** [comment]
Zenhub allows for seamless task management through github as well as the zenhub web application. We are able to prioritize tasks and issues, show support on issues, show complexity of tasks, and view burn down charts to see our progress and deadline milestones. 
We are able to upload any file type, making file sharing through github super efficient. 
Everyone is updated in real-time on any changes made in zenhub. Unread tasks/issues are marked with a blue bar which keeps everyone up to task.
We can assign tasks that can later be marked for completion, and are able to add issues with labels to better understand what needs to be completed.

**Comment by jayll** [comment]
@wkhalid2119 you need to comment on this and also make another ticket

Edit: I meant to comment on what you learned about zenhub from your research @wkhalid2119

**Comment by wkhalid2119** [comment]
Very interesting!

**Comment by wkhalid2119** [comment]
Zenhub is a versatile and powerful tool used by teams of engineers to organize the development of projects in ranging in complexity. It allows a team of users to create and document issues, request changes and updates, as well as allowing managers to assign tasks. It allows a team to track the progress of a project and figure out a concrete plan of execution.
