### ISSUE TITLE
Zenhub: Learning to use

### ISSUE THREAD

**Issue by wkhalid2119** [usman-hussain/UBEats#5]
Zenhub is a organizational system used in tech companies to create issues, service requests, ideas for features, and other general requests. It uses an intuitive and easy to use layout while still being a powerful utility for teams of engineers to accomplish tasks in an efficient manner.

**Comment by jayll** [comment]
I said comment this on the ticket! Also, you need to create a new issue for the project that is not about zenhub. @wkhalid2119
